# Generated by Django 4.2.2 on 2023-10-24 10:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/static/minicucina/images/boissons/')),
                ('nom_fichier', models.CharField(blank=True, editable=False, max_length=100)),
                ('jour', multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/static/minicucina/images/desserts/')),
                ('nom_fichier', models.CharField(blank=True, editable=False, max_length=100)),
                ('jour', multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/static/minicucina/images/entrees/')),
                ('nom_fichier', models.CharField(blank=True, editable=False, max_length=100)),
                ('jour', multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minicucina/static/minicucina/images/plats/')),
                ('nom_fichier', models.CharField(blank=True, editable=False, max_length=100)),
                ('jour', multiselectfield.db.fields.MultiSelectField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi')], default=('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'), max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
